[tls]
server = "https://ota.ce:30443"
ca_source = "file"
pkey_source = "file"
cert_source = "file"

[provision]
mode = "DeviceCred"
primary_ecu_hardware_id = "jetson-nano"
ecu_registration_endpoint = "https://ota.ce:30443/director/ecus"

[uptane]
polling_sec = 10
director_server = "https://ota.ce:30443/director"
repo_server = "https://ota.ce:30443/repo"
key_source = "tee"
key_type = "RSA2048"

[storage]
type = "sqlite"
path = "/var/lib/aktualizr"

[import]
base_path = "/var/sota/import"
tls_cacert_path = "root.crt"
tls_pkey_path = "pkey.pem"
tls_clientcert_path = "client.pem"

[pacman]
type = "none"

[bootloader]
rollback_mode = "none"
