#ifndef USER_TA_HEADER_DEFINES_H
#define USER_TA_HEADER_DEFINES_H

#include "aktualizr_ta.h"

#define TA_UUID TA_AKTUALIZR_UUID
#define TA_FLAGS TA_FLAG_SINGLE_INSTANCE
#define TA_STACK_SIZE (16 * 1024)
#define TA_DATA_SIZE (64 * 1024)

#endif /* USER_TA_HEADER_DEFINES_H */
